In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import yfinance as yf
import pandas as pd

# Download 10 stock data
START_DATE = "2023-08-30"
END_DATE = "2025-08-30"

stocks = [
    'HDFCBANK.NS',  # HDFC Bank Ltd.
    'ITC.NS',       # ITC Ltd.      
    'TCS.NS',       # Tata Consultancy Services
    'RELIANCE.NS',  # Reliance Industries Ltd.
    'COALINDIA.NS', # Coal India Ltd.
    'INFY.NS',      # Infosys Ltd.
    'BAJFINANCE.NS',# Bajaj Finance Ltd.
    'ASIANPAINT.NS',# Asian Paints Ltd.
    'LT.NS',        # Larsen & Toubro Ltd.
    'BEL.NS'        # Bharat Electronics Ltd.
]


raw_data = yf.download(stocks, start = START_DATE, end = END_DATE)

data = raw_data['Close']

[*********************100%***********************]  10 of 10 completed


In [3]:
data.head()

Ticker      ASIANPAINT.NS  BAJFINANCE.NS      BEL.NS  COALINDIA.NS  \
Date                                                                 
2023-08-30    3222.138916     719.722412  132.162598    197.842957   
2023-08-31    3184.389160     709.314880  130.836548    198.967316   
2023-09-01    3187.763428     724.921143  135.404068    204.891785   
2023-09-04    3164.291992     719.935303  138.056168    214.319077   
2023-09-05    3152.311523     727.347290  137.221207    220.848953   

Ticker      HDFCBANK.NS      INFY.NS      ITC.NS        LT.NS  RELIANCE.NS  \
Date                                                                         
2023-08-30   770.242737  1362.069092  414.485626  2663.034668  1200.142334   
2023-08-31   766.705505  1362.353638  411.583862  2656.841553  1194.657837   
2023-09-01   768.291199  1370.326050  412.847534  2656.251709  1197.461914   
2023-09-04   773.097046  1390.493774  409.524536  2665.099121  1196.494141   
2023-09-05   768.388794  1403.591309  414.766449  2686.578125  1202.896973   

Ticker           TCS.NS  
Date                     
2023-08-30  3285.771240  
2023-08-31  3252.680664  
2023-09-01  3274.385986  
2023-09-04  3312.466797  
2023-09-05  3322.980469

In [4]:
data.count()

Ticker
ASIANPAINT.NS    494
BAJFINANCE.NS    494
BEL.NS           494
COALINDIA.NS     494
HDFCBANK.NS      494
INFY.NS          494
ITC.NS           494
LT.NS            494
RELIANCE.NS      494
TCS.NS           494
dtype: int64

In [5]:
data.isnull().values.any()

np.False_

In [6]:
estimation_data = data.iloc[:248] # using half of the data for estimating mu and sigma^2

estimation_data.head()

Ticker      ASIANPAINT.NS  BAJFINANCE.NS      BEL.NS  COALINDIA.NS  \
Date                                                                 
2023-08-30    3222.138916     719.722412  132.162598    197.842957   
2023-08-31    3184.389160     709.314880  130.836548    198.967316   
2023-09-01    3187.763428     724.921143  135.404068    204.891785   
2023-09-04    3164.291992     719.935303  138.056168    214.319077   
2023-09-05    3152.311523     727.347290  137.221207    220.848953   

Ticker      HDFCBANK.NS      INFY.NS      ITC.NS        LT.NS  RELIANCE.NS  \
Date                                                                         
2023-08-30   770.242737  1362.069092  414.485626  2663.034668  1200.142334   
2023-08-31   766.705505  1362.353638  411.583862  2656.841553  1194.657837   
2023-09-01   768.291199  1370.326050  412.847534  2656.251709  1197.461914   
2023-09-04   773.097046  1390.493774  409.524536  2665.099121  1196.494141   
2023-09-05   768.388794  1403.591309  414.766449  2686.578125  1202.896973   

Ticker           TCS.NS  
Date                     
2023-08-30  3285.771240  
2023-08-31  3252.680664  
2023-09-01  3274.385986  
2023-09-04  3312.466797  
2023-09-05  3322.980469

In [7]:
estimation_data.shift(1).head()

Ticker      ASIANPAINT.NS  BAJFINANCE.NS      BEL.NS  COALINDIA.NS  \
Date                                                                 
2023-08-30            NaN            NaN         NaN           NaN   
2023-08-31    3222.138916     719.722412  132.162598    197.842957   
2023-09-01    3184.389160     709.314880  130.836548    198.967316   
2023-09-04    3187.763428     724.921143  135.404068    204.891785   
2023-09-05    3164.291992     719.935303  138.056168    214.319077   

Ticker      HDFCBANK.NS      INFY.NS      ITC.NS        LT.NS  RELIANCE.NS  \
Date                                                                         
2023-08-30          NaN          NaN         NaN          NaN          NaN   
2023-08-31   770.242737  1362.069092  414.485626  2663.034668  1200.142334   
2023-09-01   766.705505  1362.353638  411.583862  2656.841553  1194.657837   
2023-09-04   768.291199  1370.326050  412.847534  2656.251709  1197.461914   
2023-09-05   773.097046  1390.493774  409.524536  2665.099121  1196.494141   

Ticker           TCS.NS  
Date                     
2023-08-30          NaN  
2023-08-31  3285.771240  
2023-09-01  3252.680664  
2023-09-04  3274.385986  
2023-09-05  3312.466797

In [8]:
returns = estimation_data - estimation_data.shift(1)

In [9]:
returns.head()

Ticker      ASIANPAINT.NS  BAJFINANCE.NS    BEL.NS  COALINDIA.NS  HDFCBANK.NS  \
Date                                                                            
2023-08-30            NaN            NaN       NaN           NaN          NaN   
2023-08-31     -37.749756     -10.407532 -1.326050      1.124359    -3.537231   
2023-09-01       3.374268      15.606262  4.567520      5.924469     1.585693   
2023-09-04     -23.471436      -4.985840  2.652100      9.427292     4.805847   
2023-09-05     -11.980469       7.411987 -0.834961      6.529877    -4.708252   

Ticker        INFY.NS    ITC.NS      LT.NS  RELIANCE.NS     TCS.NS  
Date                                                                
2023-08-30        NaN       NaN        NaN          NaN        NaN  
2023-08-31   0.284546 -2.901764  -6.193115    -5.484497 -33.090576  
2023-09-01   7.972412  1.263672  -0.589844     2.804077  21.705322  
2023-09-04  20.167725 -3.322998   8.847412    -0.967773  38.080811  
2023-09-05  13.097534  5.241913  21.479004     6.402832  10.513672

In [10]:
returns = returns.dropna()

returns.head()

Ticker      ASIANPAINT.NS  BAJFINANCE.NS    BEL.NS  COALINDIA.NS  HDFCBANK.NS  \
Date                                                                            
2023-08-31     -37.749756     -10.407532 -1.326050      1.124359    -3.537231   
2023-09-01       3.374268      15.606262  4.567520      5.924469     1.585693   
2023-09-04     -23.471436      -4.985840  2.652100      9.427292     4.805847   
2023-09-05     -11.980469       7.411987 -0.834961      6.529877    -4.708252   
2023-09-06       1.955811       4.228394 -1.375137      0.389206    10.050659   

Ticker        INFY.NS    ITC.NS      LT.NS  RELIANCE.NS     TCS.NS  
Date                                                                
2023-08-31   0.284546 -2.901764  -6.193115    -5.484497 -33.090576  
2023-09-01   7.972412  1.263672  -0.589844     2.804077  21.705322  
2023-09-04  20.167725 -3.322998   8.847412    -0.967773  38.080811  
2023-09-05  13.097534  5.241913  21.479004     6.402832  10.513672  
2023-09-06  -1.376343  4.071869  -2.457520     2.531128   0.532959

In [11]:
import numpy as np

mu = [] # expected returns

for stock in stocks:
    mean = np.mean(returns[stock])
    mu.append(mean)

In [35]:
mu = np.array(mu) *247

In [36]:
mu

array([  41.72479248,   74.97775269, 1117.73754883,  308.3828125 ,
        267.59524536,  512.36450195,    6.73803711,  -25.51147461,
        954.03149414,  164.45269775])

In [37]:
mu.shape

(10,)

In [38]:
V = np.cov(returns, rowvar=False) * 247 # covariance matrix

In [39]:
V

array([[290272.8379343 ,  27847.20417162,   6920.19979489,
         13391.52775042,  24070.26358832,  23678.52127272,
         11384.90745016, 110761.08928844,  38132.76648614,
         83021.65502552],
       [ 27847.20417162,  30577.78547728,   5520.11946248,
          6901.9290754 ,   8770.34895145,  12168.3181607 ,
          3902.78342574,  65745.96708899,  20267.1871597 ,
         22929.33442317],
       [  6920.19979489,   5520.11946248,   9508.50107802,
          8830.57188552,   4994.50150756,   4037.29751567,
          1174.85406592,  57809.95495479,  14460.75525757,
          3129.28795017],
       [ 13391.52775042,   6901.9290754 ,   8830.57188552,
         18973.73424759,   5672.51275988,   6357.89641461,
          2286.29791658,  67974.92664765,  20859.32643072,
         12184.27361327],
       [ 24070.26358832,   8770.34895145,   4994.50150756,
          5672.51275988,  27323.86541692,   8680.03679929,
          1601.77255419,  50126.71292938,  14292.39217818,
          9

In [40]:
V.shape

(10, 10)

In [41]:
inv_V = np.linalg.inv(V)

In [42]:
inv_V

array([[ 4.24882285e-06, -1.97784131e-06,  2.10746317e-06,
        -8.29883852e-07, -2.61464708e-06,  8.16238221e-07,
        -5.45877470e-06, -1.26060228e-07, -4.14200877e-07,
        -5.56462045e-07],
       [-1.97784131e-06,  4.55421691e-05, -4.18309946e-06,
         1.52224010e-06, -5.67813733e-06, -2.09375394e-06,
        -1.54209841e-05, -1.57592281e-06, -4.58569760e-06,
         3.09416752e-07],
       [ 2.10746317e-06, -4.18309946e-06,  2.47636549e-04,
        -7.11997309e-05, -9.70461410e-06, -4.72936524e-06,
         4.02248068e-06, -9.50729911e-06, -8.34079978e-06,
         5.00357514e-06],
       [-8.29883852e-07,  1.52224010e-06, -7.11997309e-05,
         1.03317933e-04,  3.15738718e-07,  4.54613842e-07,
        -1.26997253e-05, -1.51749077e-06, -9.50406299e-06,
        -4.29407760e-07],
       [-2.61464708e-06, -5.67813733e-06, -9.70461410e-06,
         3.15738718e-07,  4.56604585e-05, -3.47709258e-06,
         3.24781812e-06, -8.63081505e-07, -2.29077226e-06,
         1.

In [43]:
inv_V.shape

(10, 10)

In [24]:
ones = np.ones(10)

In [25]:
ones.shape

(10,)

In [44]:
# Estimating optimal mean and variance

A = mu.T @ inv_V @ mu
B = mu.T @ inv_V @ ones
C = ones.T @ inv_V @ones

In [45]:
print(f"A: {A}\nB: {B}\nC: {C}")

A: 261.7152570280054
B: 0.16876170505284835
C: 0.0003350607105947639


In [46]:
D = A*C - B**2
print(f"D: {D}")

D: 0.05920998690095018


In [48]:
b = 50000
delta_1 = (1/D) * (b * C - B)
delta_2 = (1/D) * (A - b * B)

print(f"delta_1 = {delta_1}\ndelta_2 = {delta_2}")

delta_1 = 280.09250960363255
delta_2 = -138091.06239615128


In [49]:
w_opt = inv_V @ (delta_1 * mu + delta_2 * ones)

print(w_opt)

[  1.03524757  -3.83737758  47.1192488  -17.12993884  -4.35482177
   1.42951748 -25.10632435  -1.97536517   3.52547116   0.29434268]


In [52]:
w_opt.shape

(10,)

In [51]:
sum = 0

for i in w_opt:
    sum += i
    
print(sum) # should be 1

0.9999999999999833


In [53]:
estimated_returns = w_opt.T @ mu
minimized_variance = w_opt.T @ V @ w_opt

In [54]:
estimated_returns

np.float64(49999.99999999999)

In [55]:
minimized_variance

np.float64(13866534.417785475)